spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/organization?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.example.organization.entity
server:
  port: 8888
  servlet:
    context-path: /api
logging:
  level:
    com.example.organization.mapper: debug
    org.springframework.boot.autoconfigure: info
