spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/organization?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
  profiles:
    active: dev
mybatis:
  type-aliases-package: com.example.organization.entity

